ALTER TABLE users
    DROP COLUMN IF EXISTS role;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS localizacao VARCHAR(50),
    ADD COLUMN IF NOT EXISTS estado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(100);

ALTER TABLE user_interaction
    ADD COLUMN IF NOT EXISTS localizacao VARCHAR(50),
    ADD COLUMN IF NOT EXISTS estado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(100);

ALTER TABLE opinion
    ADD COLUMN IF NOT EXISTS relevancia INT;

CREATE TABLE IF NOT EXISTS context (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT
);

ALTER TABLE opinion
    ADD COLUMN IF NOT EXISTS context_id BIGINT REFERENCES context(id);
